id: P11C3512C
initial_creation_type: input
source_metadata:
  title: Āgamaśāstra (= Gauḍapādakārikā, Gauḍapādīyakārikā, a verse commentary on
    the Māṇḍūkya-Upaniṣad)
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Vedānta
  data entry: Peter Schreiner
  contribution to GRETIL: Peter Schreiner
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:55:19.634647'
last_modified_at: '2022-03-09T14:55:19.634719'
